In [1]:
import pandas as pd

values = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
index = ['one', 'two', 'three']
columns = ['A', 'B', 'C']

df = pd.DataFrame(values, index=index, columns=columns)
print(df)

       A  B  C
one    1  2  3
two    4  5  6
three  7  8  9


In [2]:
print(df.index)

Index(['one', 'two', 'three'], dtype='object')


In [3]:
Index(['one', 'two', 'three'], dtype = 'object')
print(df.colums)

NameError: name 'Index' is not defined

In [4]:
index(['one', 'two', 'three'], dtype = 'object')

TypeError: 'list' object is not callable

In [5]:
print(df.columns)

Index(['A', 'B', 'C'], dtype='object')


In [6]:
print(df.values)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
data = [
    ['1000', 'Steve', 90.72],
    ['1001', 'James', 78.09],
    ['1002', 'Doyeon', 98.43], 
    ['1003', 'Jane', 64.19], 
    ['1004', 'Pilwoong', 81.30],
    ['1005', 'Tony', 99.14],
]
df = pd.DataFrame(data)
print(df)

      0         1      2
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [8]:
df = pd.DataFrame(data, columns = ['학번', '이름', '점수'])
print(df)

     학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [9]:
print(df.head(3))

     학번      이름     점수
0  1000   Steve  90.72
1  1001   James  78.09
2  1002  Doyeon  98.43


In [10]:
print(df.tail(3))

     학번        이름     점수
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [11]:
print(df['학번'])

0    1000
1    1001
2    1002
3    1003
4    1004
5    1005
Name: 학번, dtype: object


In [12]:
import numpy as np

In [13]:
a = np.array([1, 2, 3, 4, 5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [14]:
print(a)

[1 2 3 4 5]


In [15]:
b = np.array([[10, 20, 30], [60, 70, 80]])
print(b)

[[10 20 30]
 [60 70 80]]


In [16]:
print(b.ndim)
print(b.shape)

2
(2, 3)


In [18]:
print(a.ndim)
print(a.shape)

1
(5,)


In [19]:
a = np.zeros((2, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
a = np.array(np.arrange(30)).reshape((5, 6))
print(a)

AttributeError: module 'numpy' has no attribute 'arrange'

In [2]:
import numpy as np


In [4]:
a = np.array(np.arrange(30)).reshape((5, 6))
print(a)


AttributeError: module 'numpy' has no attribute 'arrange'

In [5]:
a = np.array(np.arange(30)).reshape((5, 6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
b = a[0:2, 0:2]
print(b)

[[1 2]
 [4 5]]


In [8]:
b = a[0, :]
print(b)

[1 2 3]


In [9]:
b = a[:, 1]
print(b)

[2 5]


In [10]:
test1 = [[1, 2, 3], [4, 5, 6]]
test2 = test1[0, :]
print(test2)

TypeError: list indices must be integers or slices, not tuple

In [11]:
a = np.array([[1, 2], [4, 5], [7, 8]])
b = a[[2, 1], [1, 0]]
print(b)

[8 4]


In [12]:
a = np.array([[1, 2], [4, 5], [7, 8]])
b = a[[0, 1], [2, 0]]
print(b)

IndexError: index 2 is out of bounds for axis 1 with size 2

In [13]:
a = np.array([[1, 2], [4, 5], [7, 8]])
b = a[[0, 1], [2, 0]]
print(b)

IndexError: index 2 is out of bounds for axis 1 with size 2

In [14]:
a = np.array([[1, 2], [4, 5], [7, 8]])
b = a[[0, 1], [1, 0]]
print(b)

[2 4]


In [15]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = a[[-1, -2], [2, 0]]
print(b)

[9 4]


In [16]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = a[[-1, -3], [2, 1, 0]]
print(b)

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 